version: '3.9'

services:
  db:
    image: bitnami/postgresql:latest
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=app_user
      - POSTGRESQL_PASSWORD=app_password
      - POSTGRESQL_DATABASE=ai_cancer_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/bitnami/postgresql

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/ai_cancer_db
      - PORT=8080
      - BETTER_AUTH_SECRET=chnage-me
      - BETTER_AUTH_URL=http://localhost:8080
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@screenit.app
      - ADMIN_PASSWORD=Admin123
    ports:
      - '8080:8080'

volumes:
  db_data:
    driver: local
